POST http://localhost:3002/api/blogs HTTP/1.1
Content-Type: application/json 

{
  "username": "nbroussard - 3",
  "comment": "post 43",
  "date": "",
  "likes": 0,
  "userId": "67796a0470e786c9695ce885"
}

###

POST http://localhost:3002/api/users HTTP/1.1
Content-Type: application/json

{
  "username": "nbroussard - 3",
  "name": "Nick",
  "password": "pWord!",
  "blogs": []
}

###

POST http://localhost:3002/api/login HTTP/1.1
Content-Type: application/json

{
  "username": "nbroussard",
  "password": "pWord!"
}