POST http://localhost:3002/api/blogs HTTP/1.1
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5icm91c3NhcmQiLCJpZCI6IjY3Nzk2MmUyYjVkNTMyZDA1ZTUyN2I5YyIsImlhdCI6MTczNjAzNDAyMH0.RaNKuvtOtQ1Eb7eApLM9sQK7NziBxl9J6wWngAa_WoQ

{
  "username": "nbroussard",
  "comment": "post 21 - token auth",
  "date": "",
  "likes": 0,
  "userId": "677962e2b5d532d05e527b9c"
}

###

POST http://localhost:3002/api/users HTTP/1.1
Content-Type: application/json

{
  "username": "nbroussard - 3",
  "name": "Nick",
  "password": "pWord!",
  "blogs": []
}

###

POST http://localhost:3002/api/login HTTP/1.1
Content-Type: application/json

{
  "username": "nbroussard",
  "password": "pWord!"
}