POST http://localhost:3002/api/blogs HTTP/1.1
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5icm91c3NhcmQgLSAyIiwiaWQiOiI2NzdhYzY1OTZlNjU0N2Q5NDQ5NGU5NDQiLCJpYXQiOjE3MzYxMDMxNjF9.Qu8yn6l1NNq0Eo4TYmOeTX6IcfucyS3zT8V9jKFuHms

{
  "username": "nbroussard - 2",
  "comment": "post 2 - user 2",
  "date": "",
  "likes": 0,
  "userId": "677ac6596e6547d94494e944"
}

###

POST http://localhost:3002/api/users HTTP/1.1
Content-Type: application/json

{
  "username": "nbroussard - 2",
  "name": "Nick",
  "password": "pWord!",
  "blogs": []
}

###

// POST http://localhost:3002/api/login HTTP/1.1
// Content-Type: application/json

//{
 // "username": "nbroussard",
  //"password": "pWord!"
//}


###

POST http://localhost:3002/api/login HTTP/1.1
Content-Type: application/json

{
  "username": "nbroussard - 2",
  "password": "pWord!"
}