PUT http://localhost:3002/api/blogs/676b2994150a384a97360bf9 HTTP/1.1
Content-Type: application/json 

{
  "id": "",
  "user": "Nicholas B",
  "comment": "Hello World - PUT test - 2!",
  "date": null,
  "likes": 0
}